---
- name: check java rpm
  stat: path={{ jdk.rpm_path }}
  register: java_exists

- name: copy java
  copy :
    src: "{{ jdk.rpm_name }}"
    dest: "{{ jdk.rpm_path }}"
- name: install java from local rpm
  yum: name={{ jdk.rpm_path }}

